import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';

type Props = {
  children: React.ReactNode;
};

export default function Container({ children }: Props) {
  return (
    <>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/website-logo-small.png" />
      </Head>
      <div className="flex flex-col h-screen justify-center px-8">
        <Header />
        <main className="flex-grow flex flex-col justify-center px-8">
          {children}
        </main>
        <Footer />
      </div>
    </>
  );
}
